ReadWriteExecute/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('learnjapanese/', include('learnjapanese.urls')),
    path('', lambda req: redirect('/learnjapanese/')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views
from .forms import LJUserLoginForm

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(
        template_name='registration/login.html',
        authentication_form=LJUserLoginForm
    ), name='login'),
]

learnjapanese/urls.py
from django.urls import path

from . import views

app_name = 'learnjapanese'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/', views.CategoryListView.as_view(), name='categories_list'),
    path('category/<int:pk>', views.CategoryView.as_view(), name='category_single'),
    path('lesson/', views.LessonListView.as_view(), name='lessons_list'),
    path('lesson/create/', views.LessonCreateView.as_view(), name='lesson_create'),
    path('lesson/<int:pk>', views.LessonDetailView.as_view(), name='lesson_single'),
    path('lesson/<int:pk>/train/', views.TrainLessonStartView.as_view(), name='lesson_tr_start'),
    path('lesson/<int:pk>/train/<int:question>', views.TrainLessonView.as_view(), name='lesson_tr'),
    path('lesson/<int:pk>/train/<int:question>/submit/<int:answer>', views.TrainLessonSubmitAnswer.as_view(), name='lesson_tr_submit'),
    path('lesson/<int:pk>/train/result', views.TrainLessonResultsView.as_view(), name='lesson_tr_result'),
    path('search/', views.SearchResultView.as_view(), name='flashcard_search'),
    path('about/', views.AboutView.as_view(), name='about'),
]

learnjapanese/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name


class FlashCard(models.Model):
    english_text = models.CharField(max_length=100)
    japanese_text = models.CharField(max_length=100)
    japanese_text_kanji = models.CharField(max_length=100, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.english_text


class Lesson(models.Model):
    lesson_name = models.CharField(max_length=100)
    flash_cards = models.ManyToManyField(FlashCard)

    def __str__(self):
        return self.lesson_name

    def get_absolute_url(self):
        return reverse('learnjapanese:lesson_single', kwargs={'pk': self.pk})

learnjapanese/views.py
from django.http import HttpResponse
from django.views import generic, View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.db.models import Q

from .models import Category, FlashCard, Lesson
from .util.lesson_util import add_two_random_fcs


def index(request):
    context = {'navbar': 'home'}
    return render(request, 'learnjapanese/index.html', context)


class CategoryListView(generic.ListView):
    template_name = 'learnjapanese/categories.html'

    def get_queryset(self):
        return Category.objects.order_by('category_name')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navbar'] = 'category'
        return context


class CategoryView(generic.ListView):
    template_name = 'learnjapanese/category.html'
    context_object_name = 'flashcards_by_category'
    paginate_by = 15

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navbar'] = 'category'
        context['category'] = get_object_or_404(Category, pk=self.kwargs['pk'])
        return context

    def get_queryset(self):
        return FlashCard.objects.filter(category__pk=self.kwargs['pk']).order_by('english_text')


class LessonListView(generic.ListView):
    model = Lesson
    template_name = 'learnjapanese/lessons.html'
    context_object_name = 'lessons'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navbar'] = 'lesson'
        return context


class LessonCreateView(generic.CreateView):
    model = Lesson
    template_name = 'learnjapanese/lesson_create.html'
    fields = ['lesson_name', 'flash_cards']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navbar'] = 'lesson'
        return context


class LessonDetailView(generic.DetailView):
    model = Lesson
    template_name = 'learnjapanese/lesson.html'
    context_object_name = "lesson"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navbar'] = 'lesson'
        context['flashcards'] = self.get_object().flash_cards.all()
        return context


class TrainLessonView(generic.TemplateView):
    template_name = 'learnjapanese/lesson_train.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navbar'] = 'lesson'

        context['lesson'] = Lesson.objects.get(pk=self.kwargs.get('pk'))
        question_no = context['question'] - 1
        question_pk_list = self.request.session.get('training_question_list')
        question_pk = question_pk_list[question_no]
        context['question_obj'] = FlashCard.objects.get(pk=question_pk)
        context['answers'] = [FlashCard.objects.get(pk=answer_pk)
            for answer_pk in self.request.session['training_answer_list'][question_no]]
 
        return context
    

class TrainLessonStartView(View):
    def get(self, request, *args, **kwargs):
        '''
        Initiate training parameters in session. That includes:
        - current training id
        - last question number (0 in start view)
        - question FlashCards pks list
        - answer FlashCards pks list (list of tuples)
        - current score
        '''
        lesson_obj = Lesson.objects.get(pk=kwargs.get('pk'))
        request.session['training_id'] = kwargs.get('pk')
        request.session['training_last_question'] = 0
        
        question_list =[flashcard.id for flashcard in lesson_obj.flash_cards.all()]
        request.session['training_question_list'] = question_list
        request.session['training_answer_list'] = [add_two_random_fcs(pk) for pk in question_list]
        request.session['training_score'] = 0

        url_params = {
            'pk': request.session['training_id'],
            'question': request.session['training_last_question'] + 1,
        }
        return redirect(reverse('learnjapanese:lesson_tr', kwargs=url_params))


class TrainLessonSubmitAnswer(View):
    def get(self, request, *args, **kwargs):
        lesson_pk = kwargs.get('pk')
        answer_no = kwargs.get('answer')
        question_no = kwargs.get('question')

        # check if submit is legitimate
        if (request.session.get('training_last_question') + 1) != question_no or \
            request.session.get('training_id') != lesson_pk:
            # TODO redirect to cheat view
            pass

        # update score
        question_list = request.session['training_question_list']
        answer_list = request.session['training_answer_list']

        if question_list[question_no - 1] == answer_list[question_no - 1][answer_no]:
            request.session['training_score'] += 1
        
        # if last, redirect to results
        if question_no == len(question_list):
            url_params = {'pk': lesson_pk}
            return redirect(reverse('learnjapanese:lesson_tr_result', kwargs=url_params))
        
        # otherwise, redirect to the next question
        question_no += 1
        request.session['training_last_question'] = question_no
        url_params = {
            'pk': lesson_pk,
            'question': question_no
        }
        return redirect(reverse('learnjapanese:lesson_tr', kwargs=url_params))


class TrainLessonResultsView(generic.TemplateView):
    template_name = 'learnjapanese/lesson_train_results.html'

    def __clear_session(self):
        del self.request.session['training_id']
        del self.request.session['training_last_question']
        del self.request.session['training_question_list']
        del self.request.session['training_answer_list']
        del self.request.session['training_score']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navbar'] = 'lesson'
        context['score'] = self.request.session['training_score']
        context['lesson'] = Lesson.objects.get(pk=self.kwargs.get('pk'))
        context['lesson_len'] = len(self.request.session['training_question_list'])

        # self.__clear_session()
        return context

class TrainLessonFailView(generic.TemplateView):
    template_name = 'learnjapanese/lesson_fail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['navbar'] = 'lesson'
        return context

class SearchResultView(generic.ListView):
    model = FlashCard
    template_name = 'learnjapanese/search_results.html'
    context_object_name = 'search_results'
    paginate_by = 12

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get("q")
        return context

    def get_queryset(self):
        query = self.request.GET.get("q")
        return FlashCard.objects.filter(Q(english_text__icontains=query) | Q(japanese_text__icontains=query))


class AboutView(generic.TemplateView):
    template_name = 'learnjapanese/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navbar'] = 'about'
        return context


def todo_view(request, pk=None):
    return render(request, 'learnjapanese/todo.html', {})

learnjapanese/templates/learnjapanese/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Learn japanese - about</title>
{% endblock title %}

{% block content %}
<h2>About</h2>
<p>Site is designed to help you improve your japanese vocabulary, and maybe even your kanji recognition.
    Hope you'll have fun with it!</p>

<h3>Authors</h3>
<div id="author_cards" class="container">
    <div class="row">
        <div id="seblis_card" class="card mx-3" style="width:400px">
            <img class="card-img-top" src="{% static 'learnjapanese/avatar_seblis.jpg' %}" alt="Seblis image">
            <div class="card-body">
                <h4>Seblis</h4>
                <p class="card-text">Something about Seblis</p>
                <a href="https://www.linkedin.com/in/sebastian-lisiewski-4a479b106/" target="_blank" class="btn btn-primary">LinkedIn</a>
            </div>
        </div>
        <div id="bad_grandpa_card" class="card mx-3" style="width:400px">
            <img class="card-img-top" src="{% static 'learnjapanese/avatar_bad_grandpa.jpg' %}" alt="Bad Grandpa image">
            <div class="card-body">
                <h4>Bad Grandpa</h4>
                <p class="card-text">Something about Bad grandpa</p>
                <a href="https://www.linkedin.com/" target="_blank" class="btn btn-primary">LinkedIn</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

learnjapanese/templates/learnjapanese/categories.html
{% extends "base.html" %}

{% block title %}
<title>Learn japanese - categories</title>
{% endblock title %}

{% block content %}
<h2>Categories list</h2>

{% if category_list %}
<ul class="list-group" style="width:500px">
    {% for category in category_list %}
    <li class="list-group-item bg-light text-white text-decoration-none">
        <a href="{% url 'learnjapanese:category_single' category.id %}">
        {{ category.category_name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No categories are available.</p>
{% endif %}
{% endblock content %}

learnjapanese/templates/learnjapanese/category.html
{% extends "base.html" %}

{% block title %}
<title>Category - {{category.category_name}}</title>
{% endblock title %}

{% block content %}
<h2>Category: {{category.category_name}}</h2><br>

{% if flashcards_by_category %}
    {% for flashcard in page_obj %}
        {% if forloop.first %}<div class="row">{% endif %}
            <div class="card col-3 bg-primary text-white text-center m-4 p-4">
                English: {{flashcard.english_text}}<br><br>
                Japanese: {{flashcard.japanese_text}}
                {% if flashcard.japanese_text_kanji %}
                <br>Japanese(kanji): {{flashcard.japanese_text_kanji}}
                {% endif %}
            </div>
        {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
        {% if forloop.last %}</div>{% endif %}
    {% endfor %}

    {% include "learnjapanese/util/pagination.html" %}
{% else %}
<div class="alert alert-info">There are no flashcards for this category</div>
{% endif %}
{% endblock content %}

learnjapanese/templates/learnjapanese/index.html
{% extends "base.html" %}

{% block title %}
<title>Learn japanese - index</title>
{% endblock title %}

{% block content %}
<p>Welcome, traveler, to this accursed land called RWE website. I cannot think of any calamity that forced you to visit
    this hallowed place. May the gods bless you!</p>
<p></p>
{% endblock content%}

learnjapanese/templates/learnjapanese/lesson.html
{% extends "base.html" %}

{% block title %}
<title>Lesson</title>
{% endblock title %}

{% block content %}
<h1>You are viewing lesson {{lesson.lesson_name}}<h1>
<h3>
    FlashCards included in the lesson:
</h3>
{% for flashcard in flashcards %}
    {% if forloop.first %}<div class="row">{% endif %}
        <div class="card col-3 bg-primary text-white text-center m-4 p-4">
            English: {{flashcard.english_text}}<br><br>
            Japanese: {{flashcard.japanese_text}}
            {% if flashcard.japanese_text_kanji %}
                <br>Japanese(kanji): {{flashcard.japanese_text_kanji}}
            {% endif %}
        </div>
    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
    {% if forloop.last %}</div>{% endif %}
{% endfor %}
{% endblock content %}

learnjapanese/templates/learnjapanese/lesson_create.html
{% extends "base.html" %}

{% block title %}
<title>Learn japanese - Create Lesson</title>
{% endblock title %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

learnjapanese/templates/learnjapanese/lesson_fail.html
{% extends "base.html" %}

{% block title %}
<title>Lesson - failed</title>
{% endblock title %}

{% block content %}
Hello, sir or lady! There was some issue  with the lesson...<br>
Did you try to type url directly or to use back button? That's no good, you shouldn't do that.
{% endblock content %}

learnjapanese/templates/learnjapanese/lesson_train.html
{% extends "base.html" %}

{% block title %}
<title>Lesson - train</title>
{% endblock title %}

{% block content %}
<h1>You are training lesson {{lesson.lesson_name}}<h1>
<h2>Question number {{question}}</h2>
{% comment %} Question section {% endcomment %}
<div class="d-flex justify-content-center">
    <div class="card col-3 bg-primary text-white text-center m-4 p-4">
        <h3>English: {{question_obj.english_text}}</h3>
        {% comment %} Japanese: {{question_obj.japanese_text}} {% endcomment %}
    </div>
</div>
{% comment %} Answer section {% endcomment %}
<h3>Choose the japanese translation!</h3>
{% for answer in answers %}
    {% if forloop.first %}<div class="d-flex justify-content-center">{% endif %}
    <a class="card col-3 bg-primary text-white text-center m-4 p-4 text-decoration-none"
        href="{% url 'learnjapanese:lesson_tr_submit' lesson.id question forloop.counter0%}">
        {% comment %} English: {{answer.english_text}}<br><br>
        Japanese:  {% endcomment %}
        <h4>{{answer.japanese_text}}
            {% if answer.japanese_text_kanji %}<br>({{answer.japanese_text_kanji}}){% endif %}
        </h4>
        
    </a>
    {% if forloop.last %}</div>{% endif %}
{% endfor %}
<br>
{% endblock content %}

learnjapanese/templates/learnjapanese/lesson_train_results.html
{% extends "base.html" %}

{% block title %}
<title>Lesson - results</title>
{% endblock title %}

{% block content %}
You finished the training of the lesson {{ lesson.lesson_name }}! Your score is {{ score }} out of {{ lesson_len }}
{% endblock content %}

learnjapanese/templates/learnjapanese/lessons.html
{% extends "base.html" %}

{% block title %}
<title> Learn japanese - Lessons </title>
{% endblock title %}

{% block content %}
<a href="{% url 'learnjapanese:lesson_create' %}" class="btn btn-success mb-3">Create from scratch</a>

{% if lessons %}
<ul class="list-group col-7">
    {% for lesson in lessons %}
    <li class="list-group-item {% cycle 'bg-white' 'bg-light' %}">
        <div class="d-flex justify-content-between">
            <div class="h-100 col-8 align-self-center">
               {{ lesson.lesson_name }}
            </div>
            <div id="buttons" class="">
                <a href="{% url 'learnjapanese:lesson_single' lesson.id %}" class="btn btn-primary">View</a>
                <a href="{% url 'learnjapanese:lesson_tr_start' lesson.id %}" class="btn btn-warning">Challenge</a>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% else %}
<div class="alert alert-info">There are no lessons right now! Maybe you should create one?</div>
{% endif %}
{% endblock content %}

learnjapanese/templates/learnjapanese/search_results.html
{% extends "base.html" %}

{% block title %}
<title>Searching phrase</title>
{% endblock title %}

{% block content %}
<h2>Searching for: {{query}}</h2><br>

{% if search_results %}
    {% for flashcard in page_obj %}
        {% if forloop.first %}<div class="row">{% endif %}
            <div class="card col-3 bg-primary text-white text-center m-4 p-4">
                English: {{flashcard.english_text}}<br><br>
                Japanese: {{flashcard.japanese_text}}
            </div>
    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
    {% if forloop.last %}</div>{% endif %}
    {% endfor %}

    {% include "learnjapanese/util/pagination.html" %}
{% else %}
<div class="alert alert-info">There are no flashcards with the phrase "{{query}}" :(</div>
{% endif %}
{% endblock content %}

learnjapanese/templates/learnjapanese/todo.html
{% extends "base.html" %}

{% block title %}
<title>TODO</title>
{% endblock title %}

{% block content %}
<h1>UNDER CONSTRUCTION</h1>
{% endblock content %}