ReadWriteExecute/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('learnjapanese/', include('learnjapanese.urls')),
    path('', lambda req: redirect('/learnjapanese/')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views
from .forms import LJUserLoginForm

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(
        template_name='registration/login.html',
        authentication_form=LJUserLoginForm
    ), name='login'),
]

learnjapanese/urls.py
from django.urls import path

from . import views

app_name = 'learnjapanese'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/', views.CategoryListView.as_view(), name='categories_list'),
    path('category/<int:pk>', views.CategoryView.as_view(), name='category_single'),
    path('lesson/', views.LessonListView.as_view(), name='lessons_list'),
    path('lesson/create/', views.LessonCreateView.as_view(), name='lesson_create'),
    path('lesson/<int:pk>', views.LessonDetailView.as_view(), name='lesson_single'),
    path('lesson/<int:pk>/train/', views.TrainLessonStartView.as_view(), name='lesson_tr_start'),
    path('lesson/<int:pk>/train/<int:question>', views.TrainLessonView.as_view(), name='lesson_tr'),
    path('lesson/<int:pk>/train/<int:question>/submit/<int:answer>', views.TrainLessonSubmitAnswer.as_view(), name='lesson_tr_submit'),
    path('lesson/<int:pk>/train/result', views.TrainLessonResultsView.as_view(), name='lesson_tr_result'),
    path('search/', views.SearchResultView.as_view(), name='flashcard_search'),
    path('about/', views.AboutView.as_view(), name='about'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    {% block title %} {% endblock title %}
    {% block head %} {% endblock head %}
</head>
<body class="d-flex flex-column min-vh-100">

<div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <span class="fs-4">Read, Write, Execute</span>
        </a>

        <ul class="nav nav-pills mx-2">
            <li class="nav-item m-1">
                <a href="{% url 'learnjapanese:index' %}"
                   class="nav-link {% if navbar == 'home' %}active{% endif %}">Home</a>
            </li>
            <li class="nav-item m-1">
                <a href="{% url 'learnjapanese:categories_list' %}"
                   class="nav-link {% if navbar == 'category' %}active{% endif %}">Categories</a>
            </li>
            <li class="nav-item m-1">
                <a href="{% url 'learnjapanese:lessons_list' %}"
                   class="nav-link {% if navbar == 'lesson' %}active{% endif %}">Lesson</a>
            </li>
            <li class="nav-item m-1">
                <a href="{% url 'learnjapanese:about' %}"
                   class="nav-link {% if navbar == 'about' %}active{% endif %}">About</a>
            </li>

            <li class="nav-item m-1">
                <a href="{% url 'admin:index' %}" class="nav-link  bg-secondary text-light">Admin</a>
            </li>

            <li class="nav-item m-1">
            {% if user.is_authenticated %}
                <p class="nav-link align-middle fw-bold">Hi, {{ user.username }}</p>
            </li>
            <li>
                <a href="{% url 'logout' %}" class="nav-link  bg-secondary text-light">Log Out</a>
            {% else %}
                <a href="{% url 'login' %}" class="nav-link  bg-success text-light">Log In</a>
            </li>
            <li class="nav-item m-1">
                <a href="{% url 'accounts:signup' %}" class="nav-link  bg-warning text-light">Sign Up</a>
            {% endif %}
            </li><br>
            <li class="nav-item m-1">
                <form class="form-inline d-flex" action="{% url 'learnjapanese:flashcard_search' %}">
                    <input class="form-control mx-2" type="search" placeholder="Search a word" aria-label="Search" name="q">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </li>
        </ul>

    </header>
</div>
<div class="container">
    {% block content %} {% endblock content %}
</div>
<footer class="text-center text-lg-start bg-white text-muted mt-auto">
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
        Dictionary entries created are based on <a class="text-reset fw-bold" href="https://www.edrdg.org/jmdict/j_jmdict.html">JMDict</a> project, used according to <a class="text-reset fw-bold" href="http://www.edrdg.org/">Usage of the Dictionary Files</a>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>
</html>